method: nerf
data:
  dataset: Replica
  path: dataset/replica_semantic
  dataset_stage2: None
  path_stage2: None
  input_type: image
  dim: 3
  semantic_label: []
  skip_index: []
  pose_name: poses_bounds.npy
  extension: .png
  use_expand_depth: false
  face_img_focal: -1
  load_lrs2_times: 1
model:
  embedder: positional
  audio_embed: 4
  uv_embed: 10
  net_depth: 8
  net_width: 256
  output_ch: 4
  net_depth_fine: 8
  net_width_fine: 256
  output_ch_fine: 4
  c_dim: 256
  lambda_rgb: 1.
  audio_net: false
  use_uv_audio_sep: false
  use_coords2audio: false
  use_attention: false
  use_delta_uv: false
  use_head_pose: false
  use_head_pose_net: false
  head_pose_multires: 10
  audio_not_embed: false
  MLP_version: 'v1'
  use_audio: true
  use_audio_mel: false
  use_text: false
  use_time: false
  use_post_fusion: false
  use_post_fusion_wface: false
  use_post_fusion_blackaug: false
  post_fusion_warping: backward
  expand_lip_mask: false
  use_light_unet: false
  use_light_unet_multiscale_forward: false
  use_resnet: false
  use_resnet_layer: 6
  use_resnet_conv: 64
  post_fusion_channel: 3
  use_lms: false
  use_warplms: false
  use_canonical_depth: false
  canonical_depth_height: -1
  canonical_depth_width: -1
training:
  out_dir: log/face_simple/all_rays
  batch_size: 2048 # 64 * 1024
  batch_size_val: 512 # 32 * 1024
  print_every: 10
  checkpoint_every: 5000
  visualize_every: 500
  validate_every: 10000
  backup_every: 20000
  learning_rate: 0.0001
  scheduler_milestones: [200000, 400000]
  scheduler_gamma: 0.5
  model_selection_metric: psnr
  model_selection_mode: maximize
  n_sample_points: 64
  n_sample_points_fine: 64
  n_workers: 0
  lindisp: false
  perturb: true
  raw_noise_std: 1
  logfile: train.log
  multi_gpu: true
  use_canonical_loss: false
  use_temp_consist: false
  use_temp_consist_lip: false 
  w_loss_temp_consist_lip: 50.0
  use_loss_bg: false
  use_loss_face: false
  use_loss_facewoaudio: false
  use_loss_lip: false
  use_coords_mapping: false
  add_noise_uv: false
  add_noise_audio: false
  w_post_fusion: 1.0
  use_perceptual_loss: false
  use_perceptual_loss_mask: false
  use_lip_photo_loss: 'v1' 
  use_lip_perc_loss: 'v1'  
  use_face_photo_loss: true 
  use_face_perc_loss: true 
  w_perceptual_loss: 1.0
  use_syncloss: false
  use_sync_contrastive_loss: false
  w_syncloss: 1.0
  use_fusion_face: true
  use_c_lip: false
  fusion_lip_only: false
  use_local_ensemble: false
  use_low_resolution: false
  use_canonical_depth_loss_photo: false
  use_canonical_depth_loss_photo_v2: false
  use_canonical_depth_loss_photo_v3: false
  use_canonical_depth_loss_photo_v4: false
  use_canonical_depth_loss_photo_v5: false
  use_canonical_depth_loss_photo_v6: false
  use_canonical_depth_loss_geo: false
  use_canonical_depth_loss_geo_v2: false
  use_canonical_depth_loss_smooth: false
  use_stage2_rgb_loss: false
  use_relation_loss: false
  stage: stage1
  fix_post_net: false
  wo_post_fusion: false
test:
  eval_file_name: eval_meshes
  threshold: 0.5
  model_file: model_best.pt
  eval_crop_flag: false 
  eval_resize_flag: false 
  eval_enlarge_lip: -1
  eval_change_pose: false
  eval_change_pose_time: -1
  eval_multiscale_forward: false
  eval_post_fusion_backward_warping: false
